### ISSUE TITLE
Adding Menu Items

### ISSUE THREAD

**Issue by svaj** [commercetools/merchant-center-starter-app#13]
Hello!  I started to try and implement basic CRUD-type functionality for generic custom objects to learn how this starter app is set up. I see where I could go in and add in routes and hook them up to components, etc.  I might be missing something, but is there currently any way to add menu items to the left menu?

**Comment by emmenko** [comment]
Hey, about the menu items there is nothing you can do at the moment to change those. The default menu items are controlled within the AppShell and the "custom" menu items (e.g. for the app you are developing) will be loaded from a setting in the Merchant Center API.

The reason for that is that each application that serve one part of the MC (e.g. dashboard, products, discounts, etc) need to have and know the links for all the other apps.
In case of a custom application, since only "whitelisted" projects can access that application, menu links need to be loaded async by the navigation bar for the specific project. This will effectively allow all applications to have the correct links.

For now we will "manually" configure those settings, in the future we will provide a UI to let the users manage those settings.

If you know the projects you need to whitelist, please send me an Email with that and the links you would like to provide to the menu item. Once I've configured that, you will see the links when you access those projects.

---

> I started to try and implement basic CRUD-type functionality for generic custom objects to learn how this starter app is set up. I see where I could go in and add in routes and hook them up to components, etc.

That's great!
I hope you somehow manage to figure out what to use when and where. Until we manage to provide more documentation with best practices and so on, I suggest to look into the `@commercetools-frontend` packages to see what you can use (specifically the `application-shell` and the `ui-kit`).

Nevertheless, please open an issue here if you have any questions about those things and if there is something missing that you need.

Thanks!

**Comment by svaj** [comment]
Thanks Nicola!  This is good to know!
